INSERT INTO mycreds360.courses (course_name, description, badge, created_at, updated_at) VALUES
('Introduction to Blockchain Technology', 'Learn the basics of blockchain technology.', 'blockchain_intro', NOW(), NOW()),
('Advanced Blockchain Development', 'Deep dive into blockchain development techniques.', 'blockchain_advanced', NOW(), NOW()),
('Blockchain and Cryptocurrency', 'Understand the relationship between blockchain and cryptocurrencies.', 'blockchain_crypto', NOW(), NOW()),
('AI Fundamentals', 'Introduction to artificial intelligence concepts and techniques.', 'ai_fundamentals', NOW(), NOW()),
('Machine Learning Essentials', 'Core concepts and techniques in machine learning.', 'ml_essentials', NOW(), NOW()),
('Deep Learning with TensorFlow', 'Build and train deep learning models using TensorFlow.', 'dl_tensorflow', NOW(), NOW()),
('Architectural Design Principles', 'Learn key principles of architectural design.', 'arch_design', NOW(), NOW()),
('Modern Architecture Trends', 'Explore current trends in modern architecture.', 'arch_trends', NOW(), NOW()),
('Introduction to Programming', 'Beginner course on fundamental programming concepts.', 'intro_programming', NOW(), NOW()),
('Programming in Python', 'Comprehensive guide to programming in Python.', 'python_programming', NOW(), NOW()),
('JavaScript Basics', 'Learn the basics of JavaScript programming.', 'js_basics', NOW(), NOW()),
('Advanced JavaScript', 'In-depth JavaScript programming techniques.', 'js_advanced', NOW(), NOW()),
('Introduction to Java Programming', 'Beginner course on Java programming.', 'java_intro', NOW(), NOW()),
('Advanced Java Programming', 'Advanced topics in Java programming.', 'java_advanced', NOW(), NOW()),
('Data Engineering Foundations', 'Learn the fundamentals of data engineering.', 'data_engineering_foundations', NOW(), NOW()),
('Data Engineering with SQL', 'Build skills in data engineering using SQL.', 'data_sql', NOW(), NOW()),
('Big Data Technologies', 'Introduction to big data technologies and tools.', 'big_data_technologies', NOW(), NOW()),
('Data Warehousing Concepts', 'Learn about data warehousing and its concepts.', 'data_warehousing', NOW(), NOW()),
('Data Visualization Techniques', 'Explore techniques for visualizing data.', 'data_visualization', NOW(), NOW()),
('Introduction to AI Programming', 'Beginner course on programming for artificial intelligence.', 'ai_programming_intro', NOW(), NOW()),
('AI for Data Science', 'Apply AI techniques in data science.', 'ai_data_science', NOW(), NOW()),
('Blockchain Development for Beginners', 'Learn the basics of blockchain development.', 'blockchain_dev_beginners', NOW(), NOW()),
('Ethereum Smart Contracts', 'Develop smart contracts on the Ethereum platform.', 'ethereum_smart_contracts', NOW(), NOW()),
('Blockchain Security', 'Understand the security aspects of blockchain technology.', 'blockchain_security', NOW(), NOW()),
('Machine Learning with Python', 'Implement machine learning algorithms using Python.', 'ml_python', NOW(), NOW()),
('Deep Learning Fundamentals', 'Core principles and techniques in deep learning.', 'dl_fundamentals', NOW(), NOW()),
('Natural Language Processing with AI', 'Explore NLP techniques using AI.', 'nlp_ai', NOW(), NOW()),
('Architectural Software Tools', 'Learn about software tools used in architecture.', 'arch_software_tools', NOW(), NOW()),
('Urban Planning and Architecture', 'Study the integration of urban planning and architecture.', 'urban_planning', NOW(), NOW()),
('Introduction to Data Science', 'Beginner course on data science concepts and techniques.', 'data_science_intro', NOW(), NOW()),
('Python for Data Analysis', 'Use Python for analyzing data.', 'python_data_analysis', NOW(), NOW()),
('JavaScript for Web Development', 'Learn JavaScript for web development.', 'js_web_development', NOW(), NOW()),
('Advanced Python Programming', 'In-depth programming techniques in Python.', 'python_advanced', NOW(), NOW()),
('Data Engineering with Apache Spark', 'Learn data engineering using Apache Spark.', 'data_spark', NOW(), NOW()),
('Cloud Data Engineering', 'Understand data engineering concepts in the cloud.', 'cloud_data_engineering', NOW(), NOW()),
('AI and Machine Learning in Healthcare', 'Explore AI and machine learning applications in healthcare.', 'ai_healthcare', NOW(), NOW()),
('Architectural Design Software', 'Software tools for architectural design.', 'arch_design_software', NOW(), NOW()),
('Introduction to Web Development', 'Beginner course on web development principles.', 'web_dev_intro', NOW(), NOW()),
('Programming in C++', 'Learn C++ programming language basics and beyond.', 'cpp_programming', NOW(), NOW()),
('Data Engineering with Python', 'Use Python for data engineering tasks.', 'python_data_engineering', NOW(), NOW()),
('AI in Business Analytics', 'Apply AI techniques in business analytics.', 'ai_business_analytics', NOW(), NOW()),
('Architectural History', 'Study the history of architectural design and trends.', 'arch_history', NOW(), NOW()),
('Introduction to Cybersecurity', 'Basics of cybersecurity and its importance.', 'cybersecurity_intro', NOW(), NOW()),
('AI in Robotics', 'Explore the role of AI in robotics.', 'ai_robotics', NOW(), NOW()),
('Programming for Data Science', 'Programming skills needed for data science.', 'programming_data_science', NOW(), NOW()),
('JavaScript for Beginners', 'An introductory course on JavaScript.', 'js_for_beginners', NOW(), NOW()),
('Python for Beginners', 'Introduction to Python programming.', 'python_for_beginners', NOW(), NOW()),
('Advanced Data Engineering Concepts', 'Deep dive into advanced data engineering topics.', 'data_engineering_advanced', NOW(), NOW()),
('Architectural Drafting Techniques', 'Learn drafting techniques used in architecture.', 'arch_drafting', NOW(), NOW()),
('Introduction to Cloud Computing', 'Basics of cloud computing and its benefits.', 'cloud_computing_intro', NOW(), NOW()),
('AI in Finance', 'Applications of AI in the finance industry.', 'ai_finance', NOW(), NOW()),
('Introduction to Machine Learning', 'Beginner course on machine learning concepts.', 'ml_intro', NOW(), NOW()),
('Advanced Machine Learning Techniques', 'Explore advanced techniques in machine learning.', 'ml_advanced', NOW(), NOW()),
('Introduction to Robotics', 'Basics of robotics and its applications.', 'robotics_intro', NOW(), NOW()),
('AI and Deep Learning for Beginners', 'Beginner course on AI and deep learning.', 'ai_dl_beginners', NOW(), NOW()),
('Java Programming for Beginners', 'Learn Java programming from the ground up.', 'java_programming_beginners', NOW(), NOW()),
('Python Data Engineering', 'Data engineering tasks using Python.', 'python_data_engineering', NOW(), NOW()),
('Data Engineering with Hadoop', 'Introduction to data engineering using Hadoop.', 'data_hadoop', NOW(), NOW()),
('AI and Data Science Integration', 'Integrating AI techniques into data science workflows.', 'ai_data_science_integration', NOW(), NOW()),
('Advanced Programming Concepts in Java', 'Explore advanced programming concepts in Java.', 'java_advanced_concepts', NOW(), NOW()),
('Blockchain and Smart Contracts', 'Develop and deploy smart contracts on blockchain platforms.', 'blockchain_smart_contracts', NOW(), NOW()),
('Introduction to AI Ethics', 'Study the ethical considerations in AI development.', 'ai_ethics', NOW(), NOW()),
('Architectural Visualization', 'Techniques for visualizing architectural designs.', 'arch_visualization', NOW(), NOW()),
('Programming in Ruby', 'Learn the Ruby programming language.', 'ruby_programming', NOW(), NOW()),
('Data Engineering with Snowflake', 'Use Snowflake for data engineering tasks.', 'data_snowflake', NOW(), NOW()),
('AI in Marketing', 'Applications of AI in marketing strategies.', 'ai_marketing', NOW(), NOW()),
('Introduction to Systems Architecture', 'Learn about systems architecture and design.', 'systems_architecture_intro', NOW(), NOW()),
('Advanced Data Analysis Techniques', 'In-depth techniques for data analysis.', 'data_analysis_advanced', NOW(), NOW()),
('Programming in PHP', 'Learn PHP programming language basics.', 'php_programming', NOW(), NOW()),
('AI for Predictive Analytics', 'Use AI for predictive analytics tasks.', 'ai_predictive_analytics', NOW(), NOW()),
('Introduction to Database Management', 'Basics of managing and designing databases.', 'database_management_intro', NOW(), NOW()),
('Advanced SQL Techniques', 'In-depth SQL querying techniques.', 'sql_advanced', NOW(), NOW()),
('AI in Education', 'Explore the applications of AI in educational settings.', 'ai_education', NOW(), NOW()),
('Introduction to Software Engineering', 'Learn fundamental principles of software engineering.', 'software_engineering_intro', NOW(), NOW()),
('Programming in Swift', 'Learn Swift programming language for iOS development.', 'swift_programming', NOW(), NOW()),
('AI for Business', 'Applications of AI in various business domains.', 'ai_business', NOW(), NOW()),
('Introduction to Data Analysis with R', 'Learn data analysis techniques using R.', 'data_analysis_r', NOW(), NOW()),
('AI and Human-Computer Interaction', 'Explore the role of AI in human-computer interaction.', 'ai_hci', NOW(), NOW());
